apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitslab-goserver
  labels:
    app: bitslab-goserver
spec:
  selector:
    matchLabels:
      app: bitslab-goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: bitslab-goserver
    spec:
      containers:
      - name: bitslab-goserver
        image: bitsevil/bitslab:latest
        resources:
          requests:
            memory: 10Mi
            cpu: 100m
          limits:
            memory: 15Mi
            cpu: 200m
        ports:
        - containerPort: 5001
