apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bitslab-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bitslab-goserver
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25
