# Configurações esperadas pelo kind
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  # Role representa o papel desempenhado pelo node
  - role: control-plane
  - role: worker
  - role: worker
