apiVersion: v1
kind: Pod
metadata:
  name: goserver
  labels:
    name: goserver
spec:
  containers:
    - name: goserver
      image: betoecd/hello-go
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      # ports:
      #   - containerPort: <Port>
