apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bitslab-goserver
  labels:
    app: bitslab-goserver
spec:
  selector:
    matchLabels:
      app: bitslab-goserver
  replicas: 1
  template:
    metadata:
      name: bitslab-goserver
      labels:
        app: bitslab-goserver
    spec:
      containers:
      - name: bitslab-goserver
        image: bitsevil/bitslab:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5001
